name: py311
channels:
  - plotly
  - rapidsai
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - amqp=5.2.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - aom=3.6.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - attrs=24.3.0
  - backports.zoneinfo=0.2.1
  - billiard=4.2.1
  - blas=1.0
  - boto3=1.37.10
  - botocore=1.37.10
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - celery=5.4.0
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - click=8.1.8
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1
  - click-repl=0.2.0
  - comm=0.2.1
  - contourpy=1.3.1
  - cuda-cccl=12.4.127
  - cuda-crt-tools=12.4.131
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvcc-tools=12.4.131
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-nvvm-tools=12.4.131
  - cuda-opencl=12.4.127
  - cuda-profiler-api=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - eigen=3.4.0
  - executing=0.8.3
  - expat=2.7.1
  - faiss-gpu-cuvs=1.11.0
  - fastapi=0.112.2
  - ffmpeg=4.2.2
  - filelock=3.17.0
  - flatbuffers=24.3.25
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - gast=0.5.3
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.12.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keras=3.9.2
  - kiwisolver=1.4.8
  - kombu=5.4.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libcuvs=25.4.0
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libfaiss=1.11.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libraft-headers=25.04.00
  - libraft-headers-only=25.04.00
  - librmm=25.4.0
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.7
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.0.0
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - namex=0.0.7
  - narwhals=1.31.0
  - nbformat=5.10.4
  - nccl=2.21.5.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.3
  - nomkl=2.0
  - numexpr=2.10.2
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.5.0
  - opt_einsum=3.3.0
  - optree=0.14.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.40.0
  - platformdirs=4.3.7
  - plotly=6.0.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=5.9.0
  - psycopg2=2.9.9
  - psycopg2-binary=2.9.9
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=24.3.25
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - rapids-logger=0.1.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.22.3
  - s3transfer=0.11.2
  - scikit-learn=1.6.1
  - scipy=1.9.3
  - seaborn=0.13.2
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - starlette=0.38.2
  - sympy=1.13.3
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  # - tensorflow-gpu=2.17.0
  - termcolor=2.1.0
  - tesseract=5.2.0
  - tf-keras=2.17.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ultralytics=8.3.122
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - vine=5.1.0
  - wcwidth=0.2.5
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - x264=1!157.20191217
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - lap==0.5.12
