pipeline:
  people_detector:
    model: "Yolo"

  face_detector:
    model: "YuNet"
  
  face_recognizer:
    # model: VGG-Face
    model: Facenet512
    # model: OpenFace

general:
  output_dir: "results"
  json_size: 524288

  backup_dir: "datasets/backup"
  add_persons_dir: "datasets/new_persons"
  faces_save_dir: "datasets/data"
  features_dir: "datasets/face_features"
  gpu_id: 0

models:
  Yolo:
    device: "cuda"
    confidence_threshold: 0.7

  YuNet:
    model_path: "app/models/weights/face_detection_yunet_2023mar.onnx"
    score_threshold: 0.3
    nms_threshold: 0.3
    top_k: 5000
    device: "cpu"
    face_padding: 0.2
    confidence_threshold: 0.8

  VGG-Face:
    device: "cuda"
    confidence_threshold: 0.48

  Facenet:
    device: "cuda"
    confidence_threshold: 0.7

  Facenet512:
    device: "cuda"
    confidence_threshold: 0.7

  OpenFace:
    device: "cuda"
    confidence_threshold: 0.48
    
  DeepFace:
    device: "cuda"
    confidence_threshold: 0.48

  DeepID:
    device: "cuda"
    confidence_threshold: 0.48
            
  ArcFace:
    device: "cuda"
    confidence_threshold: 0.48

  Dlib:
    device: "cuda"
    confidence_threshold: 0.48

  SFace:
    device: "cuda"
    confidence_threshold: 0.5

  GhostFaceNet:
    device: "cuda"
    confidence_threshold: 0.5


